language: php
install:
    - composer install
    - travis_retry composer require --dev satooshi/php-coveralls
php:
  - 7.3
  - 7.2
  - 7.1

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml

after_script:
  - php vendor/bin/coveralls -v