language: php
install:
    - composer install
    - travis_retry composer require --dev php-coveralls/php-coveralls
    
php:
  - 7.3
  - 7.2

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml

after_script:
  - php vendor/bin/coveralls -v