language: php

sudo: true

php:
  - 7.2

env:
  matrix:
    - LARAVEL_VERSION=6.0.*

install: travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - composer require "illuminate/support:${LARAVEL_VERSION}"

script: vendor/bin/phpunit --verbose