language: php

sudo: true

php:
  - 7.1
  - 7.2
  - 7.3

env:
  matrix:
    - LARAVEL_VERSION=6.0.*

before_script:
  - travis_retry composer self-update
  - composer require "illuminate/support:${LARAVEL_VERSION}"